version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: dwinfotec
      MYSQL_PASSWORD: dw123456
      MYSQL_DATABASE: dwinfotec
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3306:3306'
  phpmyadmin:
    depends_on:
      - db
    links:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=dwinfotec
      - PMA_PASSWORD=dw123456
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=400M
  node:
    environment:
      - NODE_ENV=production
      - PORT=9000
    ports:
      - 9000:9000
    build:
      context: .
      dockerfile: Storage.Dockerfile
  node2:
    environment:
      # - NODE_ENV=production
      - PORT=4000

      #DB
      - DB_HOST=db
      - DB_USER=dwinfotec
      - DB_PASS=dw123456
      - DB_NAME=dwinfotec

      #JWT
      - TOKEN_SECRET=DcPa?vX2j7XGCLxg
      - TOKEN_EXPIRES_IN=10d

      #PATH FILE IMAGE
      - STORAGE_URL=http://192.168.1.39:9000
      - STORAGE_PATH=storage
      - STORAGE_PATH_SERVICE_ORDERS=service_orders

    ports:
      - 4000:4000
    build:
      context: .
      dockerfile: AppNode.Dockerfile
volumes:
  db_data: {}
  wordpress_data: {}
